### ISSUE TITLE
componentDidMount failure?

### ISSUE THREAD

**Issue by scarsam** [learn-co-curriculum/redux-thunk-lab#10]
The application seems to be working and I am using the componentDidMount method, I looked at some other solutions and didn't find a solution to this error elsewhere. I'm wondering if there is something wrong with this particular test?

```
it('should use the componentDidMount lifecycle method to fetchCats', function() {
  sinon.spy(App.prototype, 'componentDidMount');
  sinon.stub(App.prototype, 'componentDidMount');
  const {component } = setUpMount()
  expect(App.prototype.componentDidMount.calledOnce).toEqual(true);
})
```

`/redux-thunk-lab-v-000/test/app-component-test.js` on line **54**

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback.

We have updated the materials and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
