### ISSUE TITLE
App Test failed-Testing

### ISSUE THREAD

**Issue by efl7a** [learn-co-curriculum/redux-thunk-lab#11]
The App component test always failed with:
1) <App/>
       should use the componentDidMount lifecycle method to fetchCats:
     TypeError: Cannot read property 'prototype' of undefined

My code is similar to the solution, so I assume that there is a problem with the test.

**Comment by lizbur10** [comment]
You have to create a WrapperApp const and render that in index.js instead of App to get the test to pass. It's not something that's covered anywhere in the curriculum and not at all obvious from the error or the test.

**Comment by maxwellbenton** [comment]
Thank you for spotting this issue and providing feedback, @efl7a and @lizbur10.

We have updated the tests in this lab so they no longer require WrapperApp and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
