### ISSUE TITLE
UNSAT lab

### ISSUE THREAD

**Issue by micahshute** [learn-co-curriculum/redux-thunk-lab#14]
Unfortunately, this lab does little to reinforce the small amount of information presented on `thunk`, and actually teaches incorrect things. I will type out the 3 major issues with this lab for corrective purposes and also to help any students who are confused by the cloudy/incorrect/lack of information presented:

1)  There has only been one example of an action using `thunk` in the past, and the instructions in this lab for creating an action directly contradict previous examples and are vague enough that one can infer multiple different interpretations of all the wrong possible meanings, clouding the correct procedure with multiple incorrect ones. To be explicit: 

The lab states: 

>`Define your action creator function, fetchCats in src/actions/catActions. This action should use fetch to make the web request for your cat pic JSON. It should use a then function to parse the JSON of the response to this request, and another .then function chained on that to grab the actual collection of cat pic image objects. Something like:`

```javascript

fetch('http://localhost:4000/db').then(response => {
  return response.json()
}).then(responseJSON => {
  return responseJSON.images
})

```

>`Save the results of this fetch request to a const, cats, and make sure your action creator function returns an object with a type of 'FETCH_CATS' and a payload of the cats collection.`

First of all, an explicitly incorrect statement is made: `make sure your action creator function returns an object[...]` As you can see above, `action creator` is a reference to the action funciton `fetchCats()`, which, through the `thunk` middleware must return a **function** not an **object** (disregarding the technicality that in JS functions are technically subsets of objects). This is especially confusing incorrect information to present because prior to using `thunk` an action was only allowed to return plain JS objects.

So, to be clear, `fetchCats()` must return a **function**, ie 

```javascript
export function fetchCats(){
   return dispatch => {
      dispatch({/*JS object for immediate updates*/})
      return fetch(whateverURL).then(res => res.json())
                  .then(data => dispatch({/*JS object for async updates*/}))
   }
}
```

note that the inner function `return`s the whole `fetch`, which, inside the `then` performs a `dispatch`

the statement
>... the results of the fetch request  

is ambiguous, as common vernacular (ie `response` or `json`, which would explicitly reference the return values of the promises) is not used, leaving ambiguity of whether the `result` references the returned promise from fetch or the parsed JSON inside of the promise.

Even when interpeting the statement to be referencing the data inside the `then`, it turns out that the inner object referenced with the type of `FETCH_CATS` and `payload` **never** has to be returned from anywhere, it needs to be `dispatch`ed, as shown above. This description only leads one farther away from the correct solution.

The point is that the instructions are both incorrect and ambiguous about a concept minimally discussed, which teaches potentially multiple incorrect procedures for setting up this function before the correct one is discovered and the others have to be unlearned. 

2) mapDispatchToProps is never discussed in this lab or the previous lesson. Although it works the same as it did before adding `thunk`, that is not necessarily intuitive because our actions are returning a completely different datatype. Also, since we are calling our actions in the context of `dispatch`, which is a parameter to the action's returned inner function, it is reasonable to wonder if you should call the function with `dispatch` in `mapDispatchToProps`

3) Like previous labs, the requirement of the structure of the store's state is never explicitly stated in the readme or in the test, and you have to go into specific tests to see what the author's intent is. While some good ideas were presented by this structure, (ie `loading: true` in the `LOADING_CATS` action type), the value of it is diminished because it is never explained. For individuals currently doing the lab, the initial state of the catsReducer should be: 

```javascript
{ 
   loading: false,
   pictures: []
}
```

the reducer action type "LOADING_CATS" should alter `loading`s value, and "FETCH_CATS" should populate the `pictures` array

While the previous lesson can be used to solve the lab and has correct information, I know that multiple students have had to turn to 3rd party tutorials or videos just to understand the basic procedures and syntax of using `thunk` due to the content (and lack thereof) in this lab.

**Comment by thekevinhuang** [comment]
I also agree with the above concerns. The language brought up in concern 1 had me very confused until I essentially chose to ignore it and figure it out on my own.

For concern 3, one pattern I found to be extremely nice when establishing a store structure is declaring it upfront as a const. Then when setting initial state you can set it equal to the const e.g.

`const initialState = {
    loading : false,
    pictures: []
}

function reducer (state=initialState, action) {
    ...
}`

This way it is clear what is expected and what the structure will be right from the get go. Including this info in the readme would have been tremendously helpful.

**Comment by kodyclemens** [comment]
@micahshute thanks for opening this issue with your explanation, it was very helpful.

**Comment by maxwellbenton** [comment]
Hey @micahshute,

Thanks for this. I've updated this lab and the previous lesson to address some of these issues. 

1. Because there isn't enough material on thunk and the previous example is just a readme, I've converted this lab to be much more guided and have rewritten it to go through the set up of redux and thunk. The expected actions and structure have changed, but most of the code is provided in the readme now, including the structure of actions and how the action creator should be written. There is also now a section that provides a bit more context to the purpose of `LOADING_CATS`.

2. `mapStateToProps` and `mapDispatchToProps` are now used in the code-along with a working code snippet example and a note that dispatch can still be called in `App`, even though we're now dispatching in the action creator.

3. Now that it is a code-along, the state structure is provided.

I believe these changes should resolve the issues brought up here, but if not, please feel free to reopen. Thanks again for the thorough feedback!
