### ISSUE TITLE
atlanta-web-060319 issue with lab

### ISSUE THREAD

**Issue by ConradCasper** [learn-co-curriculum/redux-thunk-lab#16]
i get a 404 when I try to go to the provided url 'http://localhost:4000/db'

**Comment by maxwellbenton** [comment]
Hi @conradcasper22,

Thank you for providing this feedback. We've updated the lab so that it no longer requires the separate database, instead relying on a GitHub page that serves the same JSON data. This should prevent this issue from occuring going forward.

Thank you for contributing!

**Comment by ConradCasper** [comment]
Glad to hear!
