### ISSUE TITLE
tests do not match current instructions for lab

### ISSUE THREAD

**Issue by melzreal** [learn-co-curriculum/redux-thunk-lab#17]
FETCH_CATS should be ADD_CATS and a few other issues

**Comment by maxwellbenton** [comment]
Hey @melzreal,

Thank you for providing this feedback. This lab was recently updated, and on further investigation, it looks liked you unfortunately received only part of the updated content. My best guess based on the commits on the current lab version and the commits on your fork is that you forked just before the content was updated, receiving the old tests, but the Readme on Learn.co was displaying the updated instructions.

I've looked over the lab and confirmed that the current instructions and tests have `ADD_CATS` now in place of the previous `FETCH_CATS` action, which should mean this misalignment issue will not occur for future students.

We apologize for any frustration this may have caused you, but we appreciate you taking the time to provide feedback!

Thank you!
