### ISSUE TITLE
Should actually render

### ISSUE THREAD

**Issue by dkStephanos** [learn-co-curriculum/redux-thunk-lab#9]
This is the only lab on the entire subject, so there should actually be browser output. Even with tests passing, it is hard to tell if things actually work. Seems incomplete to complete a section on a topic without ever fully implementing said topic.

**Comment by maxwellbenton** [comment]
Thank you for providing feedback.

We have recently updated the materials for Redux in general. For this lesson in partcular, we have made sure that once all tests are passing and by using the provided cat API (https://github.com/learn-co-curriculum/cat-api), the lesson content will correctly render in browser and believe your issue to have been resolved.

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure that those who follow in your path will not encounter the same problems that you faced.

If you do not believe that this issue has been addressed, please re-open this issue. 💙
